In [9]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import numpy as np

In [11]:
data1d =np.array([1,2,3,4])

In [12]:
data2d =np.array([[1,2,3,4],[7,8,9,0]])

In [14]:
print(data1d.shape)

(4,)


In [15]:
print(data2d.shape)

(2, 4)


In [17]:
reshapeArr=data2d.reshape(4,2)
print(reshapeArr)

[[1 2]
 [3 4]
 [7 8]
 [9 0]]


In [18]:
print(data2d.ndim)

2


In [19]:
#array idexing and slicing
print(data1d[0])

1


In [20]:
data2d[1,3]

0

In [21]:
print(data1d[:3])

[1 2 3]


In [22]:
print(data2d[:, 1:])

[[2 3 4]
 [8 9 0]]


In [24]:
#Array operation
a=np.array([1,2,3])
b=np.array([4,7,8])

In [25]:
add=a+b
add

array([ 5,  9, 11])

In [26]:
mul =a*b
mul

array([ 4, 14, 24])

In [28]:
exp = np.exp(b)
exp

array([  54.59815003, 1096.63315843, 2980.95798704])

In [29]:
log = np.log(b)
log

array([1.38629436, 1.94591015, 2.07944154])

In [31]:
#broadcasting
a=np.array([1,3,4])
b=10
result=a+b
result

array([11, 13, 14])

In [33]:
#Array aggregation
data = np.array([[1,2,3],[7,8,9]])
totalSum=np.sum(data)
totalSum

30

In [34]:
columnSum=np.sum(data,axis=0)
columnSum

array([ 8, 10, 12])

In [35]:
rowMean =np.mean(data,axis=1)
rowMean

array([2., 8.])